### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by PushpenderSaini0** [souviknsl07/Covid-19-Tracker#1]
Map is not exported from 'react-leaflet' 
Below is a screenshot of the error .
![image](https://user-images.githubusercontent.com/54404738/124357519-88205900-dc39-11eb-8be1-322887ced36f.png)

This can be fixed by importing `MapContainer` from 'react-leaflet' 
reffer https://react-leaflet.js.org/docs/api-map/#mapcontainer

You can assign this to me , I will submit a PR to fix this

**Comment by souviknsl07** [comment]
@PushpenderSaini0  Actually, the thing is that when we use the MapContainer instead of the Map then it works fine on the development side but after deploying, it creates some issues. So I had to change it back to Map so that it works on the production side but then creates a problem on the development side. Don't know exactly what the problem is but had to deal with it in this way.
If you could come up with a solution to make this work on both sides then please do inform me.

**Comment by PushpenderSaini0** [comment]
What issue is created , and could you give me steps to reproduce it.
I tried to compile a production version of the app and it failed with import `Map`
but it compiles with `MapContainer` and i deployed it locally which works fine.
How can we compile it for production with `Map` import ?

![image](https://user-images.githubusercontent.com/54404738/124369648-867f8100-dc8b-11eb-88c0-5d07a81d3f1b.png)
